Add LSTM model
k2-fsa/sherpa pull request #103
Opened 2022-08-24 14:01 UTC by yaozengwei

This PR implements LSTM model. See https://github.com/k2-fsa/icefall/pull/479 for details.

2022-09-15 03:17 UTC, csukuangfj requested changes
Please also fix the conflicts and integrate the changes from
https://github.com/k2-fsa/sherpa/pull/107

2022-09-15 03:17 UTC, csukuangfj commented on sherpa/csrc/rnnt_rnn_model.h
> +  torch::Tensor ForwardEncoderProj(const torch::Tensor &encoder_out) override;
```suggestion

```

2022-09-15 03:17 UTC, csukuangfj commented on sherpa/csrc/rnnt_rnn_model.h
> +  torch::Tensor ForwardDecoderProj(const torch::Tensor &decoder_out) override;
```suggestion

```

2022-09-15 03:17 UTC, csukuangfj commented on sherpa/csrc/rnnt_rnn_model.h
> +      const torch::Tensor &projected_decoder_out) override;
```suggestion
  torch::Tensor ForwardJoiner(
      const torch::Tensor &encoder_out,
      const torch::Tensor &decoder_out) override;
```

2022-09-15 03:17 UTC, csukuangfj commented on sherpa/csrc/rnnt_rnn_model.h
> +  torch::jit::Module decoder_proj_;
```suggestion

```

2022-09-15 03:17 UTC, csukuangfj commented on sherpa/bin/lstm_transducer_stateless/beam_search.py
> +        )
Please also add

https://github.com/k2-fsa/sherpa/blob/6973dc10ddb47057f398c3c4767e1096cae9a108/sherpa/bin/pruned_stateless_emformer_rnnt2/beam_search.py#L337

2022-09-15 11:13 UTC, csukuangfj commented on .github/workflows/run-streaming-lstm-test.yaml
> +        decoding: ["greedy_search", "fast_beam_search", "fast_beam_search_nbest", "fast_beam_search_nbest_LG"]
please also add modified_beam_search.

2022-09-15 11:50 UTC, yaozengwei commented on .github/workflows/run-streaming-lstm-test.yaml
> +        decoding: ["greedy_search", "fast_beam_search", "fast_beam_search_nbest", "fast_beam_search_nbest_LG"]
OK

2022-09-16 09:26 UTC, csukuangfj approved these changes

2022-09-17 10:59 UTC, merged