added triton config for streaming zipformer
k2-fsa/sherpa pull request #430
Opened 2023-07-07 08:48 UTC by uni-saurabh-vyas

Based on https://github.com/k2-fsa/sherpa/issues/412

2023-07-07 08:52 UTC, yuekaizhang commented
Many thanks. Would you mind adding a script such that we could lauch the streaming service with one button? e.g. [build_librispeech_pruned_transducer_stateless7_streaming.sh](https://github.com/k2-fsa/sherpa/blob/master/triton/scripts/build_librispeech_pruned_transducer_stateless7_offline.sh)

2023-07-07 08:54 UTC, yuekaizhang requested changes

2023-07-07 08:54 UTC, yuekaizhang commented on triton/model_repo_streaming_zipformer/encoder/config.pbtxt.template
Would you mind using soft links for duplicate files from https://github.com/k2-fsa/sherpa/tree/master/triton/model_repo_streaming this repo?

2023-07-07 09:16 UTC, uni-saurabh-vyas commented
Yes give me one day, will push everything and add a README.md also

2023-07-07 12:03 UTC, uni-saurabh-vyas commented
@yuekaizhang I have done requested changes, and tested with bash script, triton server is up and running with all modules without any issues, also tested via decode_manifest client script I get ASR outputs.

Also, I feel readme file is not required, as build script already lists all the steps to start the server, users should be able to follow easily. Let me know if anything else required.

2023-07-07 12:10 UTC, yuekaizhang commented on triton/model_repo_streaming_zipformer/encoder/1/.gitignore
It should be a .gitkeep file.

2023-07-07 12:14 UTC, yuekaizhang commented
All config.pbtxt, config.pbtxt.template and model.py files under model_repo_streaming_zipformer/ might be same with files in model_repo_streaming except for encoder/config.pbtxt.template. Would you mind checking them? (diff file1 file2 first, then decide if we need a soft link.)


The bash scripts look nice. Thanks again.

2023-07-07 12:15 UTC, yuekaizhang commented on triton/model_repo_streaming_zipformer/decoder/config.pbtxt.template
check model_repo_streaming/decoder/config.pbtxt.template

2023-07-07 12:16 UTC, yuekaizhang commented on triton/model_repo_streaming_zipformer/feature_extractor/1/model.py
check model_repo_streaming/feature_extractor/1/model.py

2023-07-07 12:16 UTC, uni-saurabh-vyas commented
I already checked one by one, they are not same, I made some changes(for example changed type to FP32, to make it compatible with pretrained model), there was tensor name change for encoder outputs(x and x_lens from speech and speech_lengths) in python file for feature_extractor.py

The only same file is scorer/1/model.py

2023-07-07 12:16 UTC, yuekaizhang commented on triton/model_repo_streaming_zipformer/feature_extractor/config.pbtxt.template
check model_repo_streaming/feature_extractor

2023-07-07 12:16 UTC, yuekaizhang commented on triton/model_repo_streaming_zipformer/joiner/config.pbtxt.template
check check model_repo_streaming/joiner

2023-07-07 12:18 UTC, yuekaizhang commented on triton/model_repo_streaming_zipformer/transducer/config.pbtxt.template
This might be duplicate with model_repo_streaming/transducer.

2023-07-07 12:18 UTC, yuekaizhang commented on triton/model_repo_streaming_zipformer/scorer/config.pbtxt.template
check model_repo_streaming/scorer

2023-07-07 12:20 UTC, uni-saurabh-vyas commented on triton/model_repo_streaming_zipformer/transducer/config.pbtxt.template
There were some minor changes in this like changing tensor names(to make it compatible with input and output names of onnx export script (export.py))

2023-07-07 12:26 UTC, yuekaizhang commented
> I already checked one by one, they are not same, I made some changes(for example changed type to FP32, to make it compatible with pretrained model), there was tensor name change for encoder outputs(x and x_lens from speech and speech_lengths) in python file for feature_extractor.py
> 
> The only same file is scorer/1/model.py

I see. https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export.py#L811-L820 Actually, you could set --fp16 to export fp16.onnx. Then the whole model_repo could infer with fp16, which could increase throughput a lot. I was wondering if you would like try with fp16.

2023-07-07 12:28 UTC, uni-saurabh-vyas commented
Yes sure, I will try with that, didnt use that option before, will update the script(s) accordingly to make it as generic as possible

2023-07-07 12:35 UTC, yuekaizhang commented
> Also, it would be better if we make a PR https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export.py#L377-L394 to change the str "x" into "speech" "x_length" into "speech_lenghts" such that we could reuse the feature_extractor part codes.


Or https://github.com/k2-fsa/sherpa/tree/master/triton/model_repo_streaming/feature_extractor change files here and scripts/export_onnx.py, from "speech" to "x", if this way is more convenient for you.

2023-07-07 12:36 UTC, uni-saurabh-vyas commented
I am still a little bit confused as to why we have so many different export onnx scripts ?

2023-07-07 12:42 UTC, yuekaizhang commented
> I am still a little bit confused as to why we have so many different export onnx scripts ?

Ideally, we would like reuse the scripts for sherpa-onnx project. However, several minor differences block it e.g. if processed_len is regarded as a state tensor for streaming ASR. 

The WAR for now is to use scripts/build_X bash scripts to avoid confusion. Also, the difference between conformer and zipformer let us keep separte model_repo files and export scripts.

2023-07-08 05:46 UTC, uni-saurabh-vyas commented
Added the required changes.

Also tested out with fp16, the script works, however Triton gives a warning when loading.

```
I0708 04:34:38.286388 11446 model_lifecycle.cc:694] successfully loaded 'feature_extractor' version 1
2023-07-08 04:34:38.472352679 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
 can't constant fold Pow node '/Pow_1'
2023-07-08 04:34:38.472412110 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
 can't constant fold Pow node '/Pow'
2023-07-08 04:34:38.598780814 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
 can't constant fold Pow node '/Pow_1'
2023-07-08 04:34:38.598831005 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
 can't constant fold Pow node '/Pow'
2023-07-08 04:34:38.612756773 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
 can't constant fold Pow node '/Pow_1'
2023-07-08 04:34:38.612800814 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
 can't constant fold Pow node '/Pow'
2023-07-08 04:34:39.567382515 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were no
t assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT e
xplicitly assigns shape related ops to CPU to improve perf.

```

2023-07-10 02:01 UTC, yuekaizhang commented
> Added the required changes.
> 
> Also tested out with fp16, the script works, however Triton gives a warning when loading.
> 
> ```
> I0708 04:34:38.286388 11446 model_lifecycle.cc:694] successfully loaded 'feature_extractor' version 1
> 2023-07-08 04:34:38.472352679 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
>  can't constant fold Pow node '/Pow_1'
> 2023-07-08 04:34:38.472412110 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
>  can't constant fold Pow node '/Pow'
> 2023-07-08 04:34:38.598780814 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
>  can't constant fold Pow node '/Pow_1'
> 2023-07-08 04:34:38.598831005 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
>  can't constant fold Pow node '/Pow'
> 2023-07-08 04:34:38.612756773 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
>  can't constant fold Pow node '/Pow_1'
> 2023-07-08 04:34:38.612800814 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence
>  can't constant fold Pow node '/Pow'
> 2023-07-08 04:34:39.567382515 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were no
> t assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT e
> xplicitly assigns shape related ops to CPU to improve perf.
> ```

This warning is fine.

2023-07-10 02:03 UTC, yuekaizhang commented on triton/scripts/export_onnx.py
> +            "x",
This function's input names are for offline ASR, which should keep unchanged.

2023-07-10 06:05 UTC, yuekaizhang approved these changes

2023-07-10 06:07 UTC, yuekaizhang commented
Many thanks @uni-saurabh-vyas

2023-07-10 06:08 UTC, merged